---
- name: remove yum-plugin-fastestmirror
  yum: name=yum-utils state=absent

- name: add epel repository
  yum: name=epel-release state=present

- name: add docker repository
  template: src=templates/docker.repo.j2 dest=/etc/yum.repos.d/docker.repo

- name: install basic packages
  yum: name={{ item }} state=present
  with_items:
    - docker-engine
    - htop
    - lsof
    - nfs-utils
    - python-pip
    - rsync
    - strace
    - traceroute
    - vim

- name: install with python-pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - PyYAML
    - python-consul
    - docker-compose
    - docker-py

- name: force upgrade docker-compose
  command: pip install --upgrade docker-compose

- name: add media group
  group:
    name: media
    gid: 10000
    state: present

- name: add media user
  user:
    name: media
    uid: 10000
    shell: /bin/bash
    group: media
    groups: docker
    append: yes

- name: add bash_profile for media user
  template: src=templates/media.profile.j2 dest=~media/.bash_profile
