---
  # file: roles/home-server/tasks/setup-base-vm.yml
  - name: add epel repository
    yum: name=epel-release state=present

  - name: install basic packages
    yum: name={{ item }} state=present
    with_items:
      - htop
      - sysstat
      - lsof
      - nfs-utils
      - nfs4-acl-tools
      - portmap
      - rsync
      - screen
      - strace
      - traceroute
      - vim
      - unar
