---

- name: add docker repository
  template: src=templates/docker.repo.j2 dest=/etc/yum.repos.d/docker.repo

- name: install docker yum packages
  yum: name={{ item }} state=present
  with_items:
    - docker-engine
    - python-devel
    - python-setuptools
    - python-pip

# Install latest version when no specific release is set.
- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: pip, version: "latest", install: true }
    - { name: setuptools, version: "latest", install: true }
    - { name: docker-py, version: "latest", install: true }
    - { name: docker-compose, version: "latest", install: true }
  when: (item.version=="latest" and item.install)
  ignore_errors: yes

# Install specific version when set in the variables
- name: Install specific pip, setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
  with_items:
    - { name: pip, version: "latest", install: "true" }
    - { name: setuptools, version: "latest", install: "true" }
    - { name: docker-py, version: "1.9.0", install: "true" }
    - { name: docker-compose, version: "1.9.0", install: "true" }
  when: (item.version!="latest" and item.install)

# - name: install with python-pip packages
#   pip:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - PyYAML
#     - python-consul
#     - setuptools
#     - docker-py
#
# - name: ugly grab docker-compose binary
#   get_url:
#     url: https://github.com/docker/compose/releases/download/1.10.0/docker-compose-Linux-x86_64
#     dest: /usr/bin/docker-compose
#     mode: 0755
