---
- hosts: all
  become: yes
  vars_files:
    - defaults/main.yml

  tasks:
    # - include: tasks/setup-vm.yml
    # - include: tasks/setup-docker-registry.yml
    # - include: tasks/build-docker.yml
    - include: tasks/setup-vm-consul.yml
